Algoritmo "questão16"
// Disciplina   : [ALGORITIMOS]
// Professor   : palmeirence raiz.
// Autor(a)    : Thiago Dond Ferreira b.
// Data atual  : 18/10/2023

Var

sa,q,p,h: real

Inicio

Escreva("Quantidade de sanduíche a fazer:")
Leia(sa)

Q<- (100 * sa)/1000
p<- (50 * sa)/1000
h<- (100 * sa)/1000

Escreval("Queijo:", q," KG")
EScreval("Presunto:", p," KG")
Escreva("Hamburguer:",h," KG")

Fimalgoritmo