Algoritmo "questão15"
// Disciplina   : [ALGORITIMOS]
// Professor   : palmeirence raiz.
// Autor(a)    : Thiago Dond Ferreira b.
// Data atual  : 18/10/2023


Var

a,vl: inteiro
f,c: real
cent:logico

Inicio

Escreva("Digite o valor da conta:")
Leia(vl)

c<- vl div 3
a<- vl div 3
f<- (vl/3) + (vl mod 3)

Escreval("Carlos irá pagar", c)
Escreval("André irá pagar", a)
Escreva ("Felipe irá pagar", f)





Fimalgoritmo